# Generated by Django 4.2.5 on 2023-09-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='city_name',
            new_name='food',
        ),
    ]
