# Generated by Django 4.2.5 on 2023-09-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0002_rename_city_name_shop_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.food', verbose_name='Название продукта'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
    ]
