# Generated by Django 4.2.5 on 2023-10-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0003_alter_shop_food_alter_city_table_alter_food_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.shop', verbose_name='Название продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.city', verbose_name='Название продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Введите название продукта', max_length=50, verbose_name='Продукт'),
        ),
    ]
