# Generated by Django 4.2.5 on 2023-10-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0005_remove_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.city', verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.shop', verbose_name='Название продукта'),
        ),
    ]
