# Generated by Django 4.2.5 on 2023-10-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0006_shop_city_alter_food_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
