# Generated by Django 4.2.5 on 2023-10-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0012_alter_food_shop_alter_shop_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='food',
            name='weight',
        ),
    ]
