# Generated by Django 4.2.5 on 2023-10-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0013_remove_food_price_remove_food_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.shop', verbose_name='Название продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=9, verbose_name='Вес в килограммах'),
            preserve_default=False,
        ),
    ]
