# Generated by Django 4.2.5 on 2023-10-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0014_food_price_food_shop_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.city', verbose_name='Город'),
        ),
    ]
