# Generated by Django 4.2.5 on 2023-10-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodAggregatorApp', '0015_alter_food_shop_alter_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
    ]
