# Generated by Django 4.2.5 on 2023-10-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0018_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Введите свое имя', max_length=50, verbose_name='Никнейм')),
                ('comment', models.TextField(help_text='Ваш комментарий', max_length=300, verbose_name='Комментарий')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка'),
        ),
    ]
