# Generated by Django 4.2.5 on 2023-10-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0020_alter_food_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='Comment',
        ),
    ]
