# Generated by Django 4.2.5 on 2023-10-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0022_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.food', verbose_name='Продукт'),
        ),
    ]
