# Generated by Django 4.2.5 on 2023-10-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0023_comment_food_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='food_id',
            new_name='food',
        ),
    ]
