# Generated by Django 4.2.5 on 2023-10-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0025_food_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'db_table': 'FoodCategory',
            },
        ),
        migrations.RemoveField(
            model_name='food',
            name='shop',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AddField(
            model_name='food',
            name='foodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.foodcategory', verbose_name='Категория продукта'),
        ),
    ]
