# Generated by Django 4.2.5 on 2023-10-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0027_alter_foodcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип еды', max_length=50, verbose_name='Продукт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Картинка')),
            ],
            options={
                'db_table': 'food_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=50, verbose_name='Продукт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Вес в килограммах')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('foodType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.foodtype', verbose_name='Тип продукта')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.shop', verbose_name='Магазин')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории продукта'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='foodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.foodcategory', verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.product', verbose_name='Продукт'),
        ),
    ]
