# Generated by Django 4.2.5 on 2023-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0028_foodtype_product_remove_comment_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/foodCategories', verbose_name='Картинка'),
        ),
    ]
