# Generated by Django 4.2.5 on 2023-10-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0029_product_image_alter_foodtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
