# Generated by Django 4.2.5 on 2023-10-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0031_alter_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Введите название продукта', max_length=100, verbose_name='Продукт'),
        ),
    ]
