# Generated by Django 4.2.5 on 2023-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0033_productdescription_instanceofproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название категории продукта'),
        ),
    ]
