# Generated by Django 4.2.5 on 2023-10-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0035_remove_foodtype_foodcategory_foodcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='foodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodAggregatorApp.foodcategory', verbose_name='Категория продукта'),
        ),
    ]
