# Generated by Django 4.2.5 on 2023-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0036_foodtype_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Оценка'),
        ),
    ]
