# Generated by Django 4.2.5 on 2023-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0037_comment_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
