# Generated by Django 4.2.5 on 2023-10-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0038_alter_comment_mark'),
    ]
