# Generated by Django 4.2.5 on 2023-12-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAggregatorApp', '0045_rename_opened_in_shop_founded_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='image',
        ),
    ]
